require: rubocop-rspec

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 3

Layout/LineLength:
  Max: 180

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 11